kind: pipeline
type: docker
name: default

steps:
  - name: default-build
    image: node:lts-alpine
    commands:
      - ls
      - yarn install
      - yarn build
  - name: docker-build
    image: plugins/docker
    settings:
      registry: registry.docker.home:5000
      repo: registry.docker.home:5000/rpi-webtools/lynxl
      auto_tag: true
      auto_tag_suffix: linux_amd64
      insecure: true