---
version: "2"
services:
  lynxl:
    image: registry.docker.home:5000/rpi-webtools/lynxl
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: lynxl
    volumes:
      - './public/assets/:/www/assets'
    ports:
      - 8080:8080
    user: 1000:1000 # default
    environment:
      #- INIT_ASSETS=1 # default
      - INIT_ASSETS=0
    restart: always
  lynxl-backend:
    image: registry.docker.home:5000/rpi-webtools/lynxl-wl-backend
    container_name: lynxl-backend
    volumes:
      - './db:/app/db'
    ports:
      - 3000:3000
    restart: always
